//! ibsr-export: Upload IBSR report artefacts to S3 or S3-compatible storage.
//!
//! This crate provides functionality to upload report artefacts generated by
//! `ibsr-report` to S3 buckets, with support for:
//!
//! - Concurrent uploads with configurable parallelism
//! - Exponential backoff with jitter for retries
//! - Server-side encryption (SSE-S3 and SSE-KMS)
//! - S3-compatible endpoints (MinIO, R2)
//! - Presigned URL generation
//! - Upload manifest generation

pub mod cli;
pub mod content_type;
pub mod error;
pub mod file_selector;
pub mod manifest;
pub mod metadata;
pub mod presign;
pub mod upload;

pub use cli::{Cli, Command, OutputFormat, S3Args, SseMode};
pub use error::{exit_code, ExportError};
pub use file_selector::FileSelector;
pub use manifest::{ObjectInfo, UploadManifest};
pub use metadata::MetadataBuilder;
pub use presign::{parse_duration, Presigner};
pub use upload::{S3Uploader, UploadResult};
